# Site settings
title: 'Bach Do' # Your Title
tagline: 'A personal blog' # A brief tagline for your site
sidebar_image: images/lewis.jpg

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
- jekyll-paginate

paginate: 4
paginate_path: "/page:num/"


